name: Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install fyne tools
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          go install github.com/fyne-io/fyne-cross@latest

      - name: Tidy modules 
        run: |
          go mod tidy

      - name: Build for Windows
        run: fyne-cross windows --dir=./example -icon Icon.png -arch=* -app-id com.virusrpi.threedexample

      - name: Build for Android
        run: fyne-cross android --dir=./example -icon Icon.png -arch=* -app-id com.virusrpi.threedexample

      - name: Build for Linux
        run: fyne-cross linux --dir=./example -icon Icon.png -arch=* -app-id com.virusrpi.threedexample

      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./fyne-cross/dist/**
